config/routes.rb
Voicetalk::Application.routes.draw do
  resources :videos do
    resources :comments
  end
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
             controllers: {:omniauth_callbacks => "omniauth_callbacks", registrations: "registrations"}
  root to: 'home#index'

  resource :users
  match '/profile' => 'users#profile'
  match '/upload_avatar' => 'users#upload_avatar'
  match '/update_avatar' => 'users#update_avatar'

  resources :videos, :except => :index
  resources :uploads, :only => :index
  resources :zencoders, :only => :create

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: nil }
    end
  end
end

app/views/home/index.html.erb
<% unless user_signed_in? %>
    <h2>Sign up</h2>

    <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
        <% unless resource.errors.empty? %>
            <div id="error_explanation">
              <div class="alert alert-error">
                <span><%= "Please correct the following #{pluralize(resource.errors.full_messages.uniq.size, "error")}" %> </span>
                <ul style="margin: 5px 0; padding: 0">
                  <% resource.errors.full_messages.uniq.each do |msg|%>
                      <li>
                        <%= msg %>
                      </li>
                  <% end %>
                </ul>
              </div>
            </div>
        <% end %>

        <div><%= f.label :email %>
          <%= f.email_field :email, :autofocus => true %></div>

        <div><%= f.label :password %>
          <%= f.password_field :password %></div>

        <div><%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation %></div>

        <div><%= f.submit "Sign up" %></div>
    <% end %>

    <%= render "devise/shared/links" %>

<% end %>